"""Agregar llaves foraneas

Revision ID: 03a270588c46
Revises: d1cee4a7c367
Create Date: 2024-09-02 20:40:09.506008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a270588c46'
down_revision = 'd1cee4a7c367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'registro', ['dni'], ['dni'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
