"""Cambiar columnas a Text

Revision ID: 09029ae83110
Revises: 757d738981b9
Create Date: 2024-09-02 18:29:50.402195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09029ae83110'
down_revision = '757d738981b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.alter_column('campos',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.alter_column('campos',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
