"""Agregar modelo AvanceCapacidadIncidencia4

Revision ID: 0aaab7f24da9
Revises: 20b8763e26a5
Create Date: 2025-01-08 13:07:06.726590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaab7f24da9'
down_revision = '20b8763e26a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capacidad_incidencia', schema=None) as batch_op:
        batch_op.alter_column('nombre_iniciativa',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capacidad_incidencia', schema=None) as batch_op:
        batch_op.alter_column('nombre_iniciativa',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
