"""Crear cambios0710-5

Revision ID: 0b0713e0fd4f
Revises: 95c6990cf3b2
Create Date: 2024-10-07 18:28:53.255051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0713e0fd4f'
down_revision = '95c6990cf3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_caso_emblematico', schema=None) as batch_op:
        batch_op.alter_column('nombre_caso',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('ocurrencias_periodo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=350),
               existing_nullable=True)
        batch_op.alter_column('actividades_realizadas',
               existing_type=sa.TEXT(),
               type_=sa.String(length=350),
               existing_nullable=True)
        batch_op.alter_column('presencia_participacion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=350),
               existing_nullable=True)
        batch_op.alter_column('estado_actual',
               existing_type=sa.TEXT(),
               type_=sa.String(length=350),
               existing_nullable=True)
        batch_op.alter_column('recomendaciones',
               existing_type=sa.TEXT(),
               type_=sa.String(length=350),
               existing_nullable=True)
        batch_op.alter_column('otro_asunto',
               existing_type=sa.TEXT(),
               type_=sa.String(length=350),
               existing_nullable=True)
        batch_op.alter_column('responsable_registro',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_caso_emblematico', schema=None) as batch_op:
        batch_op.alter_column('responsable_registro',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('otro_asunto',
               existing_type=sa.String(length=350),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('recomendaciones',
               existing_type=sa.String(length=350),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('estado_actual',
               existing_type=sa.String(length=350),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('presencia_participacion',
               existing_type=sa.String(length=350),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('actividades_realizadas',
               existing_type=sa.String(length=350),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ocurrencias_periodo',
               existing_type=sa.String(length=350),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nombre_caso',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
