"""cambio format fechaasss

Revision ID: 0b9076fc288a
Revises: ba92fe61ed9b
Create Date: 2025-02-01 01:51:27.582850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9076fc288a'
down_revision = 'ba92fe61ed9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_politica_memoria', schema=None) as batch_op:
        batch_op.alter_column('ocurrencias_periodo',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=401),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_politica_memoria', schema=None) as batch_op:
        batch_op.alter_column('ocurrencias_periodo',
               existing_type=sa.String(length=401),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
