"""add cambios Usuario

Revision ID: 1b4144bbe11d
Revises: 4837af25501a
Create Date: 2025-08-30 13:06:54.215778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4144bbe11d'
down_revision = '4837af25501a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_iniciativa',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('iniciativa_nombre', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['iniciativa_nombre'], ['iniciativa.nombre_iniciativa'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'iniciativa_nombre'),
    sa.UniqueConstraint('user_id', 'iniciativa_nombre', name='uq_user_iniciativa')
    )
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iniciativa_oficina_regional'), ['oficina_regional'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oficina_regional', sa.String(length=60), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_users_oficina_regional'), ['oficina_regional'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_oficina_regional'))
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('oficina_regional')

    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iniciativa_oficina_regional'))

    op.drop_table('user_iniciativa')
    # ### end Alembic commands ###
