"""Agregar modelo AvanceCapacidadIncidencia14

Revision ID: 2095ebfb7eb1
Revises: a473f5db2952
Create Date: 2025-01-11 19:28:43.313088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2095ebfb7eb1'
down_revision = 'a473f5db2952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('derecho_generico', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('otro_derecho_detalle', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('oficina_regional', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('proyectos', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.drop_column('proyectos')
        batch_op.drop_column('oficina_regional')
        batch_op.drop_column('otro_derecho_detalle')
        batch_op.drop_column('derecho_generico')

    # ### end Alembic commands ###
