"""Agregar modelo AvanceCapacidadIncidencia3

Revision ID: 20b8763e26a5
Revises: 948832ce03a6
Create Date: 2025-01-08 11:56:34.970859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b8763e26a5'
down_revision = '948832ce03a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capacidad_incidencia', schema=None) as batch_op:
        batch_op.alter_column('nombre_iniciativa',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_constraint('capacidad_incidencia_registro_dni_fkey', type_='foreignkey')
        batch_op.drop_constraint('capacidad_incidencia_nombre_iniciativa_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'registro', ['registro_dni'], ['dni'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'iniciativa', ['nombre_iniciativa'], ['nombre_iniciativa'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capacidad_incidencia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('capacidad_incidencia_nombre_iniciativa_fkey', 'iniciativa', ['nombre_iniciativa'], ['nombre_iniciativa'])
        batch_op.create_foreign_key('capacidad_incidencia_registro_dni_fkey', 'registro', ['registro_dni'], ['dni'])
        batch_op.alter_column('nombre_iniciativa',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
