"""Se agrego modelo PoliticaNacionalMemoria y backend respectivo

Revision ID: 21991f495916
Revises: eb4b72ca1930
Create Date: 2024-09-09 11:24:21.810995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21991f495916'
down_revision = 'eb4b72ca1930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politica_nacional_memoria',
    sa.Column('nombre_politica_memoria', sa.String(length=255), nullable=False),
    sa.Column('localizacion', sa.String(length=255), nullable=True),
    sa.Column('descripcion_propuesta', sa.Text(), nullable=True),
    sa.Column('institucion_1', sa.String(length=255), nullable=True),
    sa.Column('asunto_1', sa.String(length=255), nullable=True),
    sa.Column('institucion_2', sa.String(length=255), nullable=True),
    sa.Column('asunto_2', sa.String(length=255), nullable=True),
    sa.Column('institucion_3', sa.String(length=255), nullable=True),
    sa.Column('asunto_3', sa.String(length=255), nullable=True),
    sa.Column('organizaciones_aliadas', sa.Text(), nullable=True),
    sa.Column('otro_dato', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nombre_politica_memoria')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('politica_nacional_memoria')
    # ### end Alembic commands ###
