"""Creacion Procesos_Iniciativas DB y creacion llaves Pk,Fk

Revision ID: 21c717c1bf73
Revises: e8dd7bdbbcb6
Create Date: 2024-09-07 22:45:28.062573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21c717c1bf73'
down_revision = 'e8dd7bdbbcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objetivo_especifico', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('logros', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sustento_logros', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contenido_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contenido_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contenido_3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contenido_4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contenido_5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contenido_6', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contenido_7', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contenido_otro', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_otro_contenido', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fase_implementacion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fase_normas_detalle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fase_institucionalizacion_detalle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fase_otro_detalle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nivel_avance_comentarios', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('componente_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_componente_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('componente_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_componente_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('componente_3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_componente_3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sustento_valoracion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('capacidad_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capacidad_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capacidad_3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capacidad_4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capacidad_5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('otra_capacidad', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('calificacion_otra_capacidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reforzar_competencias', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('participacion_comportamiento', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comentario_valoracion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('factores_favorecido', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('factores_obstaculizado', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actividad_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aporte_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actividad_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aporte_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actividad_3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aporte_3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actividad_4', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aporte_4', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actividad_5', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aporte_5', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cambios_estrategia', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comentario_relevante', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('responsable_registro', sa.String(length=255), nullable=True))
        batch_op.drop_column('responsable')
        batch_op.drop_column('fecha_inicio')
        batch_op.drop_column('descripcion_proceso')
        batch_op.drop_column('estado_actual')
        batch_op.drop_column('fecha_fin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_fin', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('estado_actual', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('descripcion_proceso', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('fecha_inicio', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('responsable', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('responsable_registro')
        batch_op.drop_column('comentario_relevante')
        batch_op.drop_column('cambios_estrategia')
        batch_op.drop_column('aporte_5')
        batch_op.drop_column('actividad_5')
        batch_op.drop_column('aporte_4')
        batch_op.drop_column('actividad_4')
        batch_op.drop_column('aporte_3')
        batch_op.drop_column('actividad_3')
        batch_op.drop_column('aporte_2')
        batch_op.drop_column('actividad_2')
        batch_op.drop_column('aporte_1')
        batch_op.drop_column('actividad_1')
        batch_op.drop_column('factores_obstaculizado')
        batch_op.drop_column('factores_favorecido')
        batch_op.drop_column('comentario_valoracion')
        batch_op.drop_column('participacion_comportamiento')
        batch_op.drop_column('reforzar_competencias')
        batch_op.drop_column('calificacion_otra_capacidad')
        batch_op.drop_column('otra_capacidad')
        batch_op.drop_column('capacidad_5')
        batch_op.drop_column('capacidad_4')
        batch_op.drop_column('capacidad_3')
        batch_op.drop_column('capacidad_2')
        batch_op.drop_column('capacidad_1')
        batch_op.drop_column('sustento_valoracion')
        batch_op.drop_column('calificacion_componente_3')
        batch_op.drop_column('componente_3')
        batch_op.drop_column('calificacion_componente_2')
        batch_op.drop_column('componente_2')
        batch_op.drop_column('calificacion_componente_1')
        batch_op.drop_column('componente_1')
        batch_op.drop_column('nivel_avance_comentarios')
        batch_op.drop_column('fase_otro_detalle')
        batch_op.drop_column('fase_institucionalizacion_detalle')
        batch_op.drop_column('fase_normas_detalle')
        batch_op.drop_column('fase_implementacion')
        batch_op.drop_column('calificacion_otro_contenido')
        batch_op.drop_column('contenido_otro')
        batch_op.drop_column('contenido_7')
        batch_op.drop_column('contenido_6')
        batch_op.drop_column('contenido_5')
        batch_op.drop_column('contenido_4')
        batch_op.drop_column('contenido_3')
        batch_op.drop_column('contenido_2')
        batch_op.drop_column('contenido_1')
        batch_op.drop_column('sustento_logros')
        batch_op.drop_column('logros')
        batch_op.drop_column('objetivo_especifico')

    # ### end Alembic commands ###
