"""Update modelo Iniciativas 1

Revision ID: 2e51ed3d9698
Revises: 2095ebfb7eb1
Create Date: 2025-01-28 01:07:28.289346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e51ed3d9698'
down_revision = '2095ebfb7eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.alter_column('fase_implementacion',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='fase_implementacion::integer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.alter_column('fase_implementacion',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
