"""Cambiar tipo de fase_implementacion a Integer

Revision ID: 30f331e07d71
Revises: 2e51ed3d9698
Create Date: 2025-01-31 22:23:59.122514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f331e07d71'
down_revision = '2e51ed3d9698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.alter_column('fase_implementacion',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='fase_implementacion::integer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.alter_column('fase_implementacion',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
