"""Inicialización de tablas3

Revision ID: 4426a9beb6d5
Revises: 66675f4061b0
Create Date: 2025-01-05 13:21:35.002091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4426a9beb6d5'
down_revision = '66675f4061b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacidad_incidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_dni', sa.String(length=20), nullable=False),
    sa.Column('nombre_iniciativa', sa.String(length=150), nullable=False),
    sa.Column('capacidad_1', sa.Integer(), nullable=True),
    sa.Column('capacidad_2', sa.Integer(), nullable=True),
    sa.Column('capacidad_3', sa.Integer(), nullable=True),
    sa.Column('capacidad_4', sa.Integer(), nullable=True),
    sa.Column('capacidad_5', sa.Integer(), nullable=True),
    sa.Column('otra_capacidad', sa.String(length=100), nullable=True),
    sa.Column('calificacion_otra_capacidad', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nombre_iniciativa'], ['iniciativa.nombre_iniciativa'], ),
    sa.ForeignKeyConstraint(['registro_dni'], ['registro.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.drop_column('capacidad_1')
        batch_op.drop_column('capacidad_3')
        batch_op.drop_column('capacidad_4')
        batch_op.drop_column('capacidad_2')
        batch_op.drop_column('capacidad_5')
        batch_op.drop_column('otra_capacidad')
        batch_op.drop_column('calificacion_otra_capacidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calificacion_otra_capacidad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otra_capacidad', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacidad_5', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacidad_2', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacidad_4', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacidad_3', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacidad_1', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('capacidad_incidencia')
    # ### end Alembic commands ###
