"""add responsable_registro a todo

Revision ID: 4837af25501a
Revises: f87a17feb03e
Create Date: 2025-08-29 23:14:11.807329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4837af25501a'
down_revision = 'f87a17feb03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_capacidad_incidencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable_registro', sa.String(length=100), nullable=True))

    with op.batch_alter_table('capacidad_incidencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable_registro', sa.String(length=100), nullable=True))

    with op.batch_alter_table('caso_emblematico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable_registro', sa.String(length=100), nullable=True))

    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable_registro', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.drop_column('responsable_registro')

    with op.batch_alter_table('caso_emblematico', schema=None) as batch_op:
        batch_op.drop_column('responsable_registro')

    with op.batch_alter_table('capacidad_incidencia', schema=None) as batch_op:
        batch_op.drop_column('responsable_registro')

    with op.batch_alter_table('avance_capacidad_incidencia', schema=None) as batch_op:
        batch_op.drop_column('responsable_registro')

    # ### end Alembic commands ###
