"""cambio formas2121as

Revision ID: 539bc907e5a3
Revises: 95282ead8be6
Create Date: 2025-02-01 02:08:44.677020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '539bc907e5a3'
down_revision = '95282ead8be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_capacidad_incidencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registr1o', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_capacidad_incidencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_registr1o')

    # ### end Alembic commands ###
