"""Crear tablas iniciales2

Revision ID: 553bba99b2d1
Revises: 081594a3e037
Create Date: 2024-09-14 01:23:35.075510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '553bba99b2d1'
down_revision = '081594a3e037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.alter_column('contenido_7',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.alter_column('contenido_7',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
