"""Añadir campos para el formulario de Iniciativa

Revision ID: 59993b3b568d
Revises: bbc712c32595
Create Date: 2024-09-02 17:39:42.221788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59993b3b568d'
down_revision = 'bbc712c32595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.alter_column('sexo',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('lugar_nacimiento',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('calle',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('comunidad',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('distrito',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('provincia',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('departamento',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('poblacion_titular',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('derecho_prioritario',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('oficina_regional',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('proyectos',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('tipo_servicios',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('servicio_actividad',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('propuesta_agenda',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('red_colectivo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('comunidad_fe',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.alter_column('comunidad_fe',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('red_colectivo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('propuesta_agenda',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('servicio_actividad',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('tipo_servicios',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('proyectos',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('oficina_regional',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('derecho_prioritario',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('poblacion_titular',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('departamento',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('provincia',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('distrito',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('comunidad',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('calle',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('lugar_nacimiento',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('sexo',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
