"""quitar fecha de edit proc ini2

Revision ID: 5d624ccb726c
Revises: 88447e6d721a
Create Date: 2025-02-01 01:18:06.992763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d624ccb726c'
down_revision = '88447e6d721a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.drop_constraint('proceso_iniciativa_numero_registro_key', type_='unique')
        batch_op.drop_column('numero_registro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_registro', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('proceso_iniciativa_numero_registro_key', ['numero_registro'])

    # ### end Alembic commands ###
