"""Inicialización de tablas2

Revision ID: 66675f4061b0
Revises: 7bf0d4350daf
Create Date: 2025-01-05 13:21:10.284762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66675f4061b0'
down_revision = '7bf0d4350daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('otra_capacidad')
        batch_op.drop_column('calificacion_otra_capacidad')
        batch_op.drop_column('capacidad_4')
        batch_op.drop_column('capacidad_2')
        batch_op.drop_column('capacidad_5')
        batch_op.drop_column('capacidad_1')
        batch_op.drop_column('capacidad_3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad_3', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacidad_1', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacidad_5', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacidad_2', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacidad_4', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('calificacion_otra_capacidad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otra_capacidad', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
