"""Agregar modelo AvanceCapacidadIncidencia9

Revision ID: 67c978929b1f
Revises: bfaecbe8b095
Create Date: 2025-01-11 16:14:16.591697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c978929b1f'
down_revision = 'bfaecbe8b095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hombres', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_mujeres', sa.Integer(), nullable=True))
        batch_op.drop_column('total_mujeres_otra')
        batch_op.drop_column('total_hombres_adolescentes')
        batch_op.drop_column('total_mujeres_adolescentes')
        batch_op.drop_column('total_mujeres_discapacidad')
        batch_op.drop_column('total_mujeres_amazonicas')
        batch_op.drop_column('total_hombres_jovenes')
        batch_op.drop_column('total_hombres_periurbanas')
        batch_op.drop_column('total_hombres_conflicto')
        batch_op.drop_column('total_mujeres_migrantes')
        batch_op.drop_column('total_hombres_amazonicas')
        batch_op.drop_column('total_hombres_migrantes')
        batch_op.drop_column('total_hombres_mujeres')
        batch_op.drop_column('total_hombres_discapacidad')
        batch_op.drop_column('total_mujeres_jovenes')
        batch_op.drop_column('total_mujeres_periurbanas')
        batch_op.drop_column('total_hombres_ninos')
        batch_op.drop_column('total_mujeres_ninos')
        batch_op.drop_column('total_mujeres_conflicto')
        batch_op.drop_column('total_hombres_otra')
        batch_op.drop_column('total_mujeres_mujeres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_mujeres_mujeres', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_hombres_otra', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_conflicto', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_ninos', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_hombres_ninos', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_periurbanas', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_jovenes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_hombres_discapacidad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_hombres_mujeres', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_hombres_migrantes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_hombres_amazonicas', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_migrantes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_hombres_conflicto', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_hombres_periurbanas', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_hombres_jovenes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_amazonicas', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_discapacidad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_adolescentes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_hombres_adolescentes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_otra', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_mujeres')
        batch_op.drop_column('total_hombres')

    # ### end Alembic commands ###
