"""Agregar modelo AvanceCapacidadIncidencia12

Revision ID: 6e3a30f92977
Revises: eadb0c1f26d7
Create Date: 2025-01-11 18:42:30.809766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3a30f92977'
down_revision = 'eadb0c1f26d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=3), nullable=True))
        batch_op.drop_column('departamento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departamento', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
