"""Update  modelo Avance Politicas o memoria y su backend

Revision ID: 6f9ec810eaf1
Revises: de9ef96b5d82
Create Date: 2024-09-09 15:15:44.100385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9ec810eaf1'
down_revision = 'de9ef96b5d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_politica_memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocurrencias_periodo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actividades_realizadas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estado_actual_gestion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recomendaciones', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('otro_asunto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('responsable_registro', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_politica_memoria', schema=None) as batch_op:
        batch_op.drop_column('responsable_registro')
        batch_op.drop_column('otro_asunto')
        batch_op.drop_column('recomendaciones')
        batch_op.drop_column('estado_actual_gestion')
        batch_op.drop_column('actividades_realizadas')
        batch_op.drop_column('ocurrencias_periodo')

    # ### end Alembic commands ###
