"""Inicialización de tablas

Revision ID: 7bf0d4350daf
Revises: 59d215143a55
Create Date: 2025-01-04 23:01:50.753757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf0d4350daf'
down_revision = '59d215143a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iniciativa_registro',
    sa.Column('iniciativa_nombre', sa.String(length=150), nullable=False),
    sa.Column('registro_dni', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['iniciativa_nombre'], ['iniciativa.nombre_iniciativa'], ),
    sa.ForeignKeyConstraint(['registro_dni'], ['registro.dni'], ),
    sa.PrimaryKeyConstraint('iniciativa_nombre', 'registro_dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iniciativa_registro')
    # ### end Alembic commands ###
