"""Creacion de Modelo AvanceCasoEmblematico y funciones AJAX para obtener num forms

Revision ID: 836ebb390396
Revises: ab9cd6677381
Create Date: 2024-09-09 01:53:46.590765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836ebb390396'
down_revision = 'ab9cd6677381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avance_caso_emblematico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_caso', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nombre_caso'], ['caso_emblematico.nombre_caso'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avance_caso_emblematico')
    # ### end Alembic commands ###
