"""Correccion en iniciativas

Revision ID: 891da9f02dcb
Revises: eb2e3ada084e
Create Date: 2024-09-11 14:30:28.635926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '891da9f02dcb'
down_revision = 'eb2e3ada084e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otra_poblacion_detalle', sa.String(length=255), nullable=True))
        batch_op.drop_column('otro_poblacion_detalle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otro_poblacion_detalle', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('otra_poblacion_detalle')

    # ### end Alembic commands ###
