"""Agregar columna num registro

Revision ID: 8ff6ed6233a2
Revises: 30f331e07d71
Create Date: 2025-02-01 01:01:30.653803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff6ed6233a2'
down_revision = '30f331e07d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_registro', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['numero_registro'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('numero_registro')

    # ### end Alembic commands ###
