"""Agregar modelo AvanceCapacidadIncidencia

Revision ID: 948832ce03a6
Revises: 4426a9beb6d5
Create Date: 2025-01-08 03:27:54.202143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948832ce03a6'
down_revision = '4426a9beb6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avance_capacidad_incidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacidad_id', sa.Integer(), nullable=False),
    sa.Column('capacidad_1', sa.Integer(), nullable=True),
    sa.Column('capacidad_2', sa.Integer(), nullable=True),
    sa.Column('capacidad_3', sa.Integer(), nullable=True),
    sa.Column('capacidad_4', sa.Integer(), nullable=True),
    sa.Column('capacidad_5', sa.Integer(), nullable=True),
    sa.Column('otra_capacidad', sa.String(length=100), nullable=True),
    sa.Column('calificacion_otra_capacidad', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capacidad_id'], ['capacidad_incidencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avance_capacidad_incidencia')
    # ### end Alembic commands ###
