"""cambio formas2

Revision ID: 95282ead8be6
Revises: 0b25681618c7
Create Date: 2025-02-01 02:03:32.185980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95282ead8be6'
down_revision = '0b25681618c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_column('fecha_registra')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registra', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
