"""cambio format fechaasssssssaaaaaaaaaaaaaaaaaaaa

Revision ID: 9bc2fdf4ff6a
Revises: e665f7f761a4
Create Date: 2025-02-01 01:59:29.624029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bc2fdf4ff6a'
down_revision = 'e665f7f761a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registroa', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_registroa')

    # ### end Alembic commands ###
