"""Agregar modelo AvanceCapacidadIncidencia13

Revision ID: a473f5db2952
Revises: 6e3a30f92977
Create Date: 2025-01-11 19:03:01.448625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a473f5db2952'
down_revision = '6e3a30f92977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departamento', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('departamento')

    # ### end Alembic commands ###
