"""Eliminación del campo DNI en Iniciativa

Revision ID: a897420f6b5a
Revises: 03a270588c46
Create Date: 2024-09-04 18:47:11.210426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a897420f6b5a'
down_revision = '03a270588c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.drop_constraint('iniciativa_ibfk_1', type_='foreignkey')
        batch_op.drop_column('dni')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dni', mysql.VARCHAR(length=20), nullable=False))
        batch_op.create_foreign_key('iniciativa_ibfk_1', 'registro', ['dni'], ['dni'])

    # ### end Alembic commands ###
