"""Creacion de Modelo Caso Emblematico y actualizacion de filter by id, name,etc

Revision ID: ab9cd6677381
Revises: 21c717c1bf73
Create Date: 2024-09-08 18:56:23.075174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9cd6677381'
down_revision = '21c717c1bf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caso_emblematico',
    sa.Column('nombre_caso', sa.String(length=255), nullable=False),
    sa.Column('numero_expediente', sa.String(length=255), nullable=False),
    sa.Column('sala', sa.String(length=255), nullable=True),
    sa.Column('antecedentes', sa.Text(), nullable=True),
    sa.Column('descripcion_caso', sa.Text(), nullable=True),
    sa.Column('numero_afectados', sa.Integer(), nullable=True),
    sa.Column('objetivo_defensa', sa.Text(), nullable=True),
    sa.Column('situacion_caso', sa.Text(), nullable=True),
    sa.Column('otro_dato', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nombre_caso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caso_emblematico')
    # ### end Alembic commands ###
