"""cambio format fechaasssssssaaaaaaaaaaaaaaaaaaaaaaa

Revision ID: b1f6aef3b956
Revises: 9bc2fdf4ff6a
Create Date: 2025-02-01 01:59:40.579428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1f6aef3b956'
down_revision = '9bc2fdf4ff6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha_registroa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registroa', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
