"""aumentar tamanio campos

Revision ID: b2d2d2718520
Revises: e4a10ebe3e35
Create Date: 2025-10-08 11:34:44.837672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d2d2718520'
down_revision = 'e4a10ebe3e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_caso_emblematico', schema=None) as batch_op:
        batch_op.alter_column('ocurrencias_periodo',
               existing_type=sa.VARCHAR(length=350),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('actividades_realizadas',
               existing_type=sa.VARCHAR(length=350),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('presencia_participacion',
               existing_type=sa.VARCHAR(length=350),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('estado_actual',
               existing_type=sa.VARCHAR(length=350),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('recomendaciones',
               existing_type=sa.VARCHAR(length=350),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('otro_asunto',
               existing_type=sa.VARCHAR(length=350),
               type_=sa.String(length=600),
               existing_nullable=True)

    with op.batch_alter_table('avance_politica_memoria', schema=None) as batch_op:
        batch_op.alter_column('ocurrencias_periodo',
               existing_type=sa.VARCHAR(length=401),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('actividades_realizadas',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('estado_actual_gestion',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('recomendaciones',
               existing_type=sa.VARCHAR(length=350),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('otro_asunto',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=600),
               existing_nullable=True)

    with op.batch_alter_table('caso_emblematico', schema=None) as batch_op:
        batch_op.alter_column('antecedentes',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('descripcion_caso',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('objetivo_defensa',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('situacion_caso',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('otro_dato',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=600),
               existing_nullable=True)

    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.alter_column('descripcion_propuesta',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('organizaciones_aliadas',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('otro_dato',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=600),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.alter_column('otro_dato',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('organizaciones_aliadas',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('descripcion_propuesta',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    with op.batch_alter_table('caso_emblematico', schema=None) as batch_op:
        batch_op.alter_column('otro_dato',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('situacion_caso',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('objetivo_defensa',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('descripcion_caso',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('antecedentes',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    with op.batch_alter_table('avance_politica_memoria', schema=None) as batch_op:
        batch_op.alter_column('otro_asunto',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('recomendaciones',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=350),
               existing_nullable=True)
        batch_op.alter_column('estado_actual_gestion',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('actividades_realizadas',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('ocurrencias_periodo',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=401),
               existing_nullable=True)

    with op.batch_alter_table('avance_caso_emblematico', schema=None) as batch_op:
        batch_op.alter_column('otro_asunto',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=350),
               existing_nullable=True)
        batch_op.alter_column('recomendaciones',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=350),
               existing_nullable=True)
        batch_op.alter_column('estado_actual',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=350),
               existing_nullable=True)
        batch_op.alter_column('presencia_participacion',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=350),
               existing_nullable=True)
        batch_op.alter_column('actividades_realizadas',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=350),
               existing_nullable=True)
        batch_op.alter_column('ocurrencias_periodo',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=350),
               existing_nullable=True)

    # ### end Alembic commands ###
