"""add cambiospolitica nac modelo

Revision ID: bb4bcf86936d
Revises: c8c17a66481d
Create Date: 2025-08-31 01:31:02.518550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4bcf86936d'
down_revision = 'c8c17a66481d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oficina_regional', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_politica_nacional_memoria_oficina_regional'), ['oficina_regional'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politica_nacional_memoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_politica_nacional_memoria_oficina_regional'))
        batch_op.drop_column('oficina_regional')

    # ### end Alembic commands ###
