"""Hacer campos numéricos y de fecha opcionales

Revision ID: bbc712c32595
Revises: 
Create Date: 2024-09-02 02:04:10.292702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbc712c32595'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.alter_column('fecha_participacion',
               existing_type=mysql.INTEGER(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.alter_column('fecha_participacion',
               existing_type=sa.Date(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
