"""Agregar modelo AvanceCapacidadIncidencia8

Revision ID: bfaecbe8b095
Revises: e7019a15e23a
Create Date: 2025-01-11 14:46:33.603537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfaecbe8b095'
down_revision = 'e7019a15e23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.drop_column('otro_derecho_detalle')
        batch_op.drop_column('derecho_generico')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('derecho_generico', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otro_derecho_detalle', sa.VARCHAR(length=60), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
