"""add cambios caso emblematico modelo

Revision ID: c8c17a66481d
Revises: 1b4144bbe11d
Create Date: 2025-08-30 23:28:15.986352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c17a66481d'
down_revision = '1b4144bbe11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso_emblematico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oficina_regional', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_caso_emblematico_oficina_regional'), ['oficina_regional'], unique=False)




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_iniciativa', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_iniciativa', type_='unique')

    with op.batch_alter_table('caso_emblematico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caso_emblematico_oficina_regional'))
        batch_op.drop_column('oficina_regional')

    # ### end Alembic commands ###
