"""cambio ptmr1

Revision ID: d2e249b6d397
Revises: c3fc1311afb4
Create Date: 2025-02-01 04:29:47.051171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2e249b6d397'
down_revision = 'c3fc1311afb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro1', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_registro1')

    # ### end Alembic commands ###
