"""Se agrego modelo Avance Politicas o memoria y su backend

Revision ID: de9ef96b5d82
Revises: 21991f495916
Create Date: 2024-09-09 13:33:49.518087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9ef96b5d82'
down_revision = '21991f495916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avance_politica_memoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_politica_memoria', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nombre_politica_memoria'], ['politica_nacional_memoria.nombre_politica_memoria'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avance_politica_memoria')
    # ### end Alembic commands ###
