"""add participacion_iniciativa table

Revision ID: e4a10ebe3e35
Revises: bb4bcf86936d
Create Date: 2025-09-21 13:33:12.872759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a10ebe3e35'
down_revision = 'bb4bcf86936d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participacion_iniciativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciativa_nombre', sa.String(length=150), nullable=False),
    sa.Column('registro_dni', sa.String(length=12), nullable=True),
    sa.Column('nombre_participante', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('cambiado_por', sa.String(length=100), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['iniciativa_nombre'], ['iniciativa.nombre_iniciativa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registro_dni'], ['registro.dni'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iniciativa_nombre', 'registro_dni', name='uq_participacion_ultima')
    )
    with op.batch_alter_table('participacion_iniciativa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participacion_iniciativa_iniciativa_nombre'), ['iniciativa_nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_participacion_iniciativa_registro_dni'), ['registro_dni'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participacion_iniciativa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participacion_iniciativa_registro_dni'))
        batch_op.drop_index(batch_op.f('ix_participacion_iniciativa_iniciativa_nombre'))

    op.drop_table('participacion_iniciativa')
    # ### end Alembic commands ###
