"""cambio format fechaasssssssaaaaaaaaaa

Revision ID: e665f7f761a4
Revises: 36f4c20b78e0
Create Date: 2025-02-01 01:53:41.633240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e665f7f761a4'
down_revision = '36f4c20b78e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_politica_memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha_registro1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_politica_memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro1', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
