"""Agregar modelo AvanceCapacidadIncidencia7

Revision ID: e7019a15e23a
Revises: 0aaab7f24da9
Create Date: 2025-01-08 14:42:27.815663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7019a15e23a'
down_revision = '0aaab7f24da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_capacidad_incidencia', schema=None) as batch_op:
        batch_op.drop_constraint('avance_capacidad_incidencia_capacidad_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'capacidad_incidencia', ['capacidad_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_capacidad_incidencia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('avance_capacidad_incidencia_capacidad_id_fkey', 'capacidad_incidencia', ['capacidad_id'], ['id'])

    # ### end Alembic commands ###
