"""Agregar modelo AvanceCapacidadIncidencia11

Revision ID: eadb0c1f26d7
Revises: 0acf9f957258
Create Date: 2025-01-11 18:17:54.422342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eadb0c1f26d7'
down_revision = '0acf9f957258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_participacion_fe', sa.String(length=80), nullable=True))

    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('otro_poblacion')
        batch_op.drop_column('comunidad_fe')
        batch_op.drop_column('tipo_participacion_fe')
        batch_op.drop_column('propuesta_agenda')
        batch_op.drop_column('tipo_servicios')
        batch_op.drop_column('red_detalle')
        batch_op.drop_column('fe_detalle')
        batch_op.drop_column('fecha_participacion')
        batch_op.drop_column('poblacion_titular')
        batch_op.drop_column('red_colectivo')
        batch_op.drop_column('derecho_prioritario')
        batch_op.drop_column('oficina_regional')
        batch_op.drop_column('otro_derecho')
        batch_op.drop_column('agenda_detalle')
        batch_op.drop_column('servicio_actividad')
        batch_op.drop_column('proyectos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proyectos', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('servicio_actividad', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('agenda_detalle', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otro_derecho', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('oficina_regional', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('derecho_prioritario', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('red_colectivo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('poblacion_titular', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_participacion', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fe_detalle', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('red_detalle', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_servicios', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('propuesta_agenda', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_participacion_fe', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comunidad_fe', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otro_poblacion', sa.VARCHAR(length=60), autoincrement=False, nullable=True))

    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.drop_column('tipo_participacion_fe')

    # ### end Alembic commands ###
