"""Correccion en iniciativas

Revision ID: eb2e3ada084e
Revises: 6f9ec810eaf1
Create Date: 2024-09-11 13:43:20.199196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2e3ada084e'
down_revision = '6f9ec810eaf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hombres_ninos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_ninos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_hombres_adolescentes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_adolescentes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_hombres_jovenes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_jovenes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_hombres_mujeres', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_mujeres', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_hombres_discapacidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_discapacidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_hombres_migrantes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_migrantes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_hombres_amazonicas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_amazonicas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_hombres_periurbanas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_periurbanas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_hombres_conflicto', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_conflicto', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_hombres_otra', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_mujeres_otra', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cambio_politica_detalle', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cambio_marcos_detalle', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cambio_practicas_detalle', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cambio_sensibilidad_detalle', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iniciativa', schema=None) as batch_op:
        batch_op.drop_column('cambio_sensibilidad_detalle')
        batch_op.drop_column('cambio_practicas_detalle')
        batch_op.drop_column('cambio_marcos_detalle')
        batch_op.drop_column('cambio_politica_detalle')
        batch_op.drop_column('total_mujeres_otra')
        batch_op.drop_column('total_hombres_otra')
        batch_op.drop_column('total_mujeres_conflicto')
        batch_op.drop_column('total_hombres_conflicto')
        batch_op.drop_column('total_mujeres_periurbanas')
        batch_op.drop_column('total_hombres_periurbanas')
        batch_op.drop_column('total_mujeres_amazonicas')
        batch_op.drop_column('total_hombres_amazonicas')
        batch_op.drop_column('total_mujeres_migrantes')
        batch_op.drop_column('total_hombres_migrantes')
        batch_op.drop_column('total_mujeres_discapacidad')
        batch_op.drop_column('total_hombres_discapacidad')
        batch_op.drop_column('total_mujeres_mujeres')
        batch_op.drop_column('total_hombres_mujeres')
        batch_op.drop_column('total_mujeres_jovenes')
        batch_op.drop_column('total_hombres_jovenes')
        batch_op.drop_column('total_mujeres_adolescentes')
        batch_op.drop_column('total_hombres_adolescentes')
        batch_op.drop_column('total_mujeres_ninos')
        batch_op.drop_column('total_hombres_ninos')

    # ### end Alembic commands ###
