"""Modificacion de Modelo AvanceCasoEmblematico y su function 

Revision ID: eb4b72ca1930
Revises: 836ebb390396
Create Date: 2024-09-09 03:32:32.192150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4b72ca1930'
down_revision = '836ebb390396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_caso_emblematico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocurrencias_periodo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actividades_realizadas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('presencia_participacion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estado_actual', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recomendaciones', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('otro_asunto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('responsable_registro', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avance_caso_emblematico', schema=None) as batch_op:
        batch_op.drop_column('responsable_registro')
        batch_op.drop_column('otro_asunto')
        batch_op.drop_column('recomendaciones')
        batch_op.drop_column('estado_actual')
        batch_op.drop_column('presencia_participacion')
        batch_op.drop_column('actividades_realizadas')
        batch_op.drop_column('ocurrencias_periodo')

    # ### end Alembic commands ###
