"""cambio ptmr2

Revision ID: f1515cc62a2b
Revises: d2e249b6d397
Create Date: 2025-02-01 04:29:58.163795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1515cc62a2b'
down_revision = 'd2e249b6d397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha_registro1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_iniciativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro1', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
