"""cambio formatdate2

Revision ID: f46e288e6957
Revises: c53643954ddf
Create Date: 2025-02-01 03:42:53.374675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f46e288e6957'
down_revision = 'c53643954ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha_registro1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro1', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
