"""add responsable_registro to registro

Revision ID: f87a17feb03e
Revises: f1515cc62a2b
Create Date: 2025-08-29 22:52:46.798655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87a17feb03e'
down_revision = 'f1515cc62a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable_registro', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('responsable_registro')

    # ### end Alembic commands ###
